export const GETDATA_SUCCESS="GETDATA_SUCCESS"
export const GETDATA_REQUEST="GETDATA_REQUEST"
export const GETDATA_FALIAURE="GETDATA_FALIAURE"

export const SINGLE_GET_PRODUCT_REQUEST="SINGLE_GET_PRODUCT_REQUEST"
export const SINGLE_GET_PRODUCT_SUCCESS="SINGLE_GET_PRODUCT_SUCCESS"
export const SINGLE_GET_PRODUCT_FALIURE="SINGLE_GET_PRODUCT_FALIURE" 