export const GETDATA_SUCCESS="GETDATA_SUCCESS"
export const GETDATA_REQUEST="GETDATA_REQUEST"
export const GETDATA_FALIAURE="GETDATA_FALIAURE"

export const SINGLE_GET_PRODUCT_REQUEST="SINGLE_GET_PRODUCT_REQUEST"
export const SINGLE_GET_PRODUCT_SUCCESS="SINGLE_GET_PRODUCT_SUCCESS"
export const SINGLE_GET_PRODUCT_FALIURE="SINGLE_GET_PRODUCT_FALIURE" 

export const ADD_TOCART_REQUEST="ADD_TOCART_REQUEST"
export const ADD_TOCART_SUCCESS="ADD_TOCART_SUCCESS"
export const ADD_TOCART_FAILURE="ADD_TOCART_FAILURE"

export const GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_FALIURE="GET_CART_FALIURE"

export const DELETE_FROM_CART="DELETE_FROM_CART"


export const ADD_ADDRESS_REQUEST="ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS="ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAILURE="ADD_ADDRESS_FAILURE"


export const GET_ADDRESS_REQUEST="GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS="GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FALIURE="GET_ADDRESS_FALIURE"